// Multi-Language Learning Data
// Frequency-based data for spaced repetition learning

// Language configurations
const languageConfig = {
    japanese: {
        title: 'Japanese Learning App',
        subtitle: 'Master Hiragana, Katakana & Kanji with Spaced Repetition',
        modes: ['characters', 'words', 'sentences'],
        charactersLabel: 'Hiragana/Katakana/Kanji'
    },
    french: {
        title: 'French Learning App',
        subtitle: 'Master French Alphabet & Vocabulary with Spaced Repetition',
        modes: ['characters', 'words', 'sentences'],
        charactersLabel: 'Alphabet & Accents'
    },
    gujarati: {
        title: 'Gujarati Learning App',
        subtitle: 'Master Gujarati Script & Vocabulary with Spaced Repetition',
        modes: ['characters', 'words', 'sentences'],
        charactersLabel: 'Gujarati Script'
    }
};

// Character to pronunciation mapping for hover tooltips
const charToRomaji = {
    // Hiragana
    'あ': 'a', 'い': 'i', 'う': 'u', 'え': 'e', 'お': 'o',
    'か': 'ka', 'き': 'ki', 'く': 'ku', 'け': 'ke', 'こ': 'ko',
    'が': 'ga', 'ぎ': 'gi', 'ぐ': 'gu', 'げ': 'ge', 'ご': 'go',
    'さ': 'sa', 'し': 'shi', 'す': 'su', 'せ': 'se', 'そ': 'so',
    'ざ': 'za', 'じ': 'ji', 'ず': 'zu', 'ぜ': 'ze', 'ぞ': 'zo',
    'た': 'ta', 'ち': 'chi', 'つ': 'tsu', 'て': 'te', 'と': 'to',
    'だ': 'da', 'ぢ': 'dji', 'づ': 'dzu', 'で': 'de', 'ど': 'do',
    'な': 'na', 'に': 'ni', 'ぬ': 'nu', 'ね': 'ne', 'の': 'no',
    'は': 'ha', 'ひ': 'hi', 'ふ': 'fu', 'へ': 'he', 'ほ': 'ho',
    'ば': 'ba', 'び': 'bi', 'ぶ': 'bu', 'べ': 'be', 'ぼ': 'bo',
    'ぱ': 'pa', 'ぴ': 'pi', 'ぷ': 'pu', 'ぺ': 'pe', 'ぽ': 'po',
    'ま': 'ma', 'み': 'mi', 'む': 'mu', 'め': 'me', 'も': 'mo',
    'や': 'ya', 'ゆ': 'yu', 'よ': 'yo',
    'ら': 'ra', 'り': 'ri', 'る': 'ru', 'れ': 're', 'ろ': 'ro',
    'わ': 'wa', 'ゐ': 'wi', 'ゑ': 'we', 'を': 'wo', 'ん': 'n',
    // Katakana
    'ア': 'a', 'イ': 'i', 'ウ': 'u', 'エ': 'e', 'オ': 'o',
    'カ': 'ka', 'キ': 'ki', 'ク': 'ku', 'ケ': 'ke', 'コ': 'ko',
    'ガ': 'ga', 'ギ': 'gi', 'グ': 'gu', 'ゲ': 'ge', 'ゴ': 'go',
    'サ': 'sa', 'シ': 'shi', 'ス': 'su', 'セ': 'se', 'ソ': 'so',
    'ザ': 'za', 'ジ': 'ji', 'ズ': 'zu', 'ゼ': 'ze', 'ゾ': 'zo',
    'タ': 'ta', 'チ': 'chi', 'ツ': 'tsu', 'テ': 'te', 'ト': 'to',
    'ダ': 'da', 'ヂ': 'dji', 'ヅ': 'dzu', 'デ': 'de', 'ド': 'do',
    'ナ': 'na', 'ニ': 'ni', 'ヌ': 'nu', 'ネ': 'ne', 'ノ': 'no',
    'ハ': 'ha', 'ヒ': 'hi', 'フ': 'fu', 'ヘ': 'he', 'ホ': 'ho',
    'バ': 'ba', 'ビ': 'bi', 'ブ': 'bu', 'ベ': 'be', 'ボ': 'bo',
    'パ': 'pa', 'ピ': 'pi', 'プ': 'pu', 'ペ': 'pe', 'ポ': 'po',
    'マ': 'ma', 'ミ': 'mi', 'ム': 'mu', 'メ': 'me', 'モ': 'mo',
    'ヤ': 'ya', 'ユ': 'yu', 'ヨ': 'yo',
    'ラ': 'ra', 'リ': 'ri', 'ル': 'ru', 'レ': 're', 'ロ': 'ro',
    'ワ': 'wa', 'ヰ': 'wi', 'ヱ': 'we', 'ヲ': 'wo', 'ン': 'n',
    // Punctuation and particles
    '？': '?', '！': '!', '、': ',', '。': '.',

    // French alphabet
    'a': 'a', 'b': 'b', 'c': 'c', 'd': 'd', 'e': 'e', 'f': 'f', 'g': 'g', 'h': 'h', 'i': 'i', 'j': 'j',
    'k': 'k', 'l': 'l', 'm': 'm', 'n': 'n', 'o': 'o', 'p': 'p', 'q': 'q', 'r': 'r', 's': 's', 't': 't',
    'u': 'u', 'v': 'v', 'w': 'w', 'x': 'x', 'y': 'y', 'z': 'z',
    'A': 'A', 'B': 'B', 'C': 'C', 'D': 'D', 'E': 'E', 'F': 'F', 'G': 'G', 'H': 'H', 'I': 'I', 'J': 'J',
    'K': 'K', 'L': 'L', 'M': 'M', 'N': 'N', 'O': 'O', 'P': 'P', 'Q': 'Q', 'R': 'R', 'S': 'S', 'T': 'T',
    'U': 'U', 'V': 'V', 'W': 'W', 'X': 'X', 'Y': 'Y', 'Z': 'Z',
    'é': 'é', 'è': 'è', 'ê': 'ê', 'ë': 'ë', 'à': 'à', 'â': 'â', 'ù': 'ù', 'û': 'û',
    'ô': 'ô', 'î': 'î', 'ï': 'ï', 'ç': 'ç', 'œ': 'œ', 'æ': 'æ', 'ÿ': 'ÿ',

    // Gujarati vowels
    'અ': 'a', 'આ': 'ā', 'ઇ': 'i', 'ઈ': 'ī', 'ઉ': 'u', 'ઊ': 'ū', 'ઋ': 'ṛ',
    'એ': 'e', 'ઐ': 'ai', 'ઓ': 'o', 'ઔ': 'au',
    // Gujarati consonants
    'ક': 'ka', 'ખ': 'kha', 'ગ': 'ga', 'ઘ': 'gha', 'ઙ': 'ṅa',
    'ચ': 'ca', 'છ': 'cha', 'જ': 'ja', 'ઝ': 'jha', 'ઞ': 'ña',
    'ટ': 'ṭa', 'ઠ': 'ṭha', 'ડ': 'ḍa', 'ઢ': 'ḍha', 'ણ': 'ṇa',
    'ત': 'ta', 'થ': 'tha', 'દ': 'da', 'ધ': 'dha', 'ન': 'na',
    'પ': 'pa', 'ફ': 'pha', 'બ': 'ba', 'ભ': 'bha', 'મ': 'ma',
    'ય': 'ya', 'ર': 'ra', 'લ': 'la', 'વ': 'va',
    'શ': 'śa', 'ષ': 'ṣa', 'સ': 'sa', 'હ': 'ha', 'ળ': 'ḷa', 'ક્ષ': 'kṣa', 'જ્ઞ': 'jña',

    // Common kanji
    '人': 'hito', '日': 'hi/nichi', '一': 'ichi', '国': 'kuni',
    '会': 'kai', '年': 'nen', '大': 'dai', '十': 'juu',
    '二': 'ni', '本': 'hon', '中': 'naka', '長': 'nagai',
    '出': 'de', '三': 'san', '時': 'ji/toki', '行': 'i(ku)',
    '見': 'mi(ru)', '月': 'tsuki', '分': 'wa(karu)', '後': 'ato',
    '前': 'mae', '生': 'i(kiru)', '五': 'go', '間': 'kan',
    '上': 'ue', '東': 'higashi', '四': 'yon', '今': 'ima',
    '金': 'kane', '九': 'kyuu', '入': 'iru', '学': 'gaku',
    '高': 'takai', '円': 'en', '子': 'ko', '外': 'soto',
    '八': 'hachi', '六': 'roku', '下': 'shita', '来': 'ku(ru)',
    '気': 'ki', '小': 'chiisai', '七': 'nana', '山': 'yama',
    '話': 'hana(su)', '女': 'onna', '北': 'kita', '午': 'go',
    '百': 'hyaku', '書': 'ka(ku)', '語': 'go', '読': 'yo(mu)',
    '聞': 'ki(ku)', '強': 'benkyo', '事': 'koto', '校': 'kou',
    '先': 'sen', '私': 'watashi', '元': 'gen', '何': 'nani',
    '度': 'do', '願': 'nega(i)', '腹': 'hara', '空': 'a(ku)',
    '勉': 'ben', '仕': 'shi', '天': 'ten', '食': 'ta(beru)',
    '飲': 'no(mu)', '聞': 'ki(ku)', 'お': 'o', 'は': 'wa', 'が': 'ga',
    'を': 'wo', 'に': 'ni', 'で': 'de', 'か': 'ka', 'ね': 'ne',
    'よ': 'yo', 'す': 'su', 'ま': 'ma'
};

const japaneseData = {
    hiragana: [
        // Basic 46 characters (by frequency)
        { char: 'あ', romaji: 'a', meaning: 'a sound', frequency: 1 },
        { char: 'い', romaji: 'i', meaning: 'i sound', frequency: 2 },
        { char: 'う', romaji: 'u', meaning: 'u sound', frequency: 3 },
        { char: 'え', romaji: 'e', meaning: 'e sound', frequency: 4 },
        { char: 'お', romaji: 'o', meaning: 'o sound', frequency: 5 },
        { char: 'か', romaji: 'ka', meaning: 'ka sound', frequency: 6 },
        { char: 'き', romaji: 'ki', meaning: 'ki sound', frequency: 7 },
        { char: 'く', romaji: 'ku', meaning: 'ku sound', frequency: 8 },
        { char: 'け', romaji: 'ke', meaning: 'ke sound', frequency: 9 },
        { char: 'こ', romaji: 'ko', meaning: 'ko sound', frequency: 10 },
        { char: 'さ', romaji: 'sa', meaning: 'sa sound', frequency: 11 },
        { char: 'し', romaji: 'shi', meaning: 'shi sound', frequency: 12 },
        { char: 'す', romaji: 'su', meaning: 'su sound', frequency: 13 },
        { char: 'せ', romaji: 'se', meaning: 'se sound', frequency: 14 },
        { char: 'そ', romaji: 'so', meaning: 'so sound', frequency: 15 },
        { char: 'た', romaji: 'ta', meaning: 'ta sound', frequency: 16 },
        { char: 'ち', romaji: 'chi', meaning: 'chi sound', frequency: 17 },
        { char: 'つ', romaji: 'tsu', meaning: 'tsu sound', frequency: 18 },
        { char: 'て', romaji: 'te', meaning: 'te sound', frequency: 19 },
        { char: 'と', romaji: 'to', meaning: 'to sound', frequency: 20 },
        { char: 'な', romaji: 'na', meaning: 'na sound', frequency: 21 },
        { char: 'に', romaji: 'ni', meaning: 'ni sound', frequency: 22 },
        { char: 'ぬ', romaji: 'nu', meaning: 'nu sound', frequency: 23 },
        { char: 'ね', romaji: 'ne', meaning: 'ne sound', frequency: 24 },
        { char: 'の', romaji: 'no', meaning: 'no sound', frequency: 25 },
        { char: 'は', romaji: 'ha', meaning: 'ha sound', frequency: 26 },
        { char: 'ひ', romaji: 'hi', meaning: 'hi sound', frequency: 27 },
        { char: 'ふ', romaji: 'fu', meaning: 'fu sound', frequency: 28 },
        { char: 'へ', romaji: 'he', meaning: 'he sound', frequency: 29 },
        { char: 'ほ', romaji: 'ho', meaning: 'ho sound', frequency: 30 },
        { char: 'ま', romaji: 'ma', meaning: 'ma sound', frequency: 31 },
        { char: 'み', romaji: 'mi', meaning: 'mi sound', frequency: 32 },
        { char: 'む', romaji: 'mu', meaning: 'mu sound', frequency: 33 },
        { char: 'め', romaji: 'me', meaning: 'me sound', frequency: 34 },
        { char: 'も', romaji: 'mo', meaning: 'mo sound', frequency: 35 },
        { char: 'や', romaji: 'ya', meaning: 'ya sound', frequency: 36 },
        { char: 'ゆ', romaji: 'yu', meaning: 'yu sound', frequency: 37 },
        { char: 'よ', romaji: 'yo', meaning: 'yo sound', frequency: 38 },
        { char: 'ら', romaji: 'ra', meaning: 'ra sound', frequency: 39 },
        { char: 'り', romaji: 'ri', meaning: 'ri sound', frequency: 40 },
        { char: 'る', romaji: 'ru', meaning: 'ru sound', frequency: 41 },
        { char: 'れ', romaji: 're', meaning: 're sound', frequency: 42 },
        { char: 'ろ', romaji: 'ro', meaning: 'ro sound', frequency: 43 },
        { char: 'わ', romaji: 'wa', meaning: 'wa sound', frequency: 44 },
        { char: 'を', romaji: 'wo', meaning: 'wo particle', frequency: 45 },
        { char: 'ん', romaji: 'n', meaning: 'n sound', frequency: 46 }
    ],

    katakana: [
        // Basic 46 characters
        { char: 'ア', romaji: 'a', meaning: 'a sound', frequency: 1 },
        { char: 'イ', romaji: 'i', meaning: 'i sound', frequency: 2 },
        { char: 'ウ', romaji: 'u', meaning: 'u sound', frequency: 3 },
        { char: 'エ', romaji: 'e', meaning: 'e sound', frequency: 4 },
        { char: 'オ', romaji: 'o', meaning: 'o sound', frequency: 5 },
        { char: 'カ', romaji: 'ka', meaning: 'ka sound', frequency: 6 },
        { char: 'キ', romaji: 'ki', meaning: 'ki sound', frequency: 7 },
        { char: 'ク', romaji: 'ku', meaning: 'ku sound', frequency: 8 },
        { char: 'ケ', romaji: 'ke', meaning: 'ke sound', frequency: 9 },
        { char: 'コ', romaji: 'ko', meaning: 'ko sound', frequency: 10 },
        { char: 'サ', romaji: 'sa', meaning: 'sa sound', frequency: 11 },
        { char: 'シ', romaji: 'shi', meaning: 'shi sound', frequency: 12 },
        { char: 'ス', romaji: 'su', meaning: 'su sound', frequency: 13 },
        { char: 'セ', romaji: 'se', meaning: 'se sound', frequency: 14 },
        { char: 'ソ', romaji: 'so', meaning: 'so sound', frequency: 15 },
        { char: 'タ', romaji: 'ta', meaning: 'ta sound', frequency: 16 },
        { char: 'チ', romaji: 'chi', meaning: 'chi sound', frequency: 17 },
        { char: 'ツ', romaji: 'tsu', meaning: 'tsu sound', frequency: 18 },
        { char: 'テ', romaji: 'te', meaning: 'te sound', frequency: 19 },
        { char: 'ト', romaji: 'to', meaning: 'to sound', frequency: 20 },
        { char: 'ナ', romaji: 'na', meaning: 'na sound', frequency: 21 },
        { char: 'ニ', romaji: 'ni', meaning: 'ni sound', frequency: 22 },
        { char: 'ヌ', romaji: 'nu', meaning: 'nu sound', frequency: 23 },
        { char: 'ネ', romaji: 'ne', meaning: 'ne sound', frequency: 24 },
        { char: 'ノ', romaji: 'no', meaning: 'no sound', frequency: 25 },
        { char: 'ハ', romaji: 'ha', meaning: 'ha sound', frequency: 26 },
        { char: 'ヒ', romaji: 'hi', meaning: 'hi sound', frequency: 27 },
        { char: 'フ', romaji: 'fu', meaning: 'fu sound', frequency: 28 },
        { char: 'ヘ', romaji: 'he', meaning: 'he sound', frequency: 29 },
        { char: 'ホ', romaji: 'ho', meaning: 'ho sound', frequency: 30 },
        { char: 'マ', romaji: 'ma', meaning: 'ma sound', frequency: 31 },
        { char: 'ミ', romaji: 'mi', meaning: 'mi sound', frequency: 32 },
        { char: 'ム', romaji: 'mu', meaning: 'mu sound', frequency: 33 },
        { char: 'メ', romaji: 'me', meaning: 'me sound', frequency: 34 },
        { char: 'モ', romaji: 'mo', meaning: 'mo sound', frequency: 35 },
        { char: 'ヤ', romaji: 'ya', meaning: 'ya sound', frequency: 36 },
        { char: 'ユ', romaji: 'yu', meaning: 'yu sound', frequency: 37 },
        { char: 'ヨ', romaji: 'yo', meaning: 'yo sound', frequency: 38 },
        { char: 'ラ', romaji: 'ra', meaning: 'ra sound', frequency: 39 },
        { char: 'リ', romaji: 'ri', meaning: 'ri sound', frequency: 40 },
        { char: 'ル', romaji: 'ru', meaning: 'ru sound', frequency: 41 },
        { char: 'レ', romaji: 're', meaning: 're sound', frequency: 42 },
        { char: 'ロ', romaji: 'ro', meaning: 'ro sound', frequency: 43 },
        { char: 'ワ', romaji: 'wa', meaning: 'wa sound', frequency: 44 },
        { char: 'ヲ', romaji: 'wo', meaning: 'wo particle', frequency: 45 },
        { char: 'ン', romaji: 'n', meaning: 'n sound', frequency: 46 }
    ],

    kanji: [
        // Most common kanji (JLPT N5 and high frequency)
        { char: '人', romaji: 'hito/jin', meaning: 'person, human', frequency: 1, example: '人 (ひと) - person' },
        { char: '日', romaji: 'hi/nichi', meaning: 'day, sun', frequency: 2, example: '今日 (きょう) - today' },
        { char: '一', romaji: 'ichi', meaning: 'one', frequency: 3, example: '一つ (ひとつ) - one thing' },
        { char: '国', romaji: 'kuni/koku', meaning: 'country', frequency: 4, example: '国 (くに) - country' },
        { char: '会', romaji: 'kai', meaning: 'meeting, association', frequency: 5, example: '会う (あう) - to meet' },
        { char: '年', romaji: 'nen/toshi', meaning: 'year', frequency: 6, example: '今年 (ことし) - this year' },
        { char: '大', romaji: 'dai/oo', meaning: 'big, large', frequency: 7, example: '大きい (おおきい) - big' },
        { char: '十', romaji: 'juu', meaning: 'ten', frequency: 8, example: '十 (じゅう) - ten' },
        { char: '二', romaji: 'ni', meaning: 'two', frequency: 9, example: '二つ (ふたつ) - two things' },
        { char: '本', romaji: 'hon/moto', meaning: 'book, origin', frequency: 10, example: '本 (ほん) - book' },
        { char: '中', romaji: 'chuu/naka', meaning: 'middle, inside', frequency: 11, example: '中 (なか) - inside' },
        { char: '長', romaji: 'chou/nagai', meaning: 'long, chief', frequency: 12, example: '長い (ながい) - long' },
        { char: '出', romaji: 'shutsu/deru', meaning: 'exit, to go out', frequency: 13, example: '出る (でる) - to exit' },
        { char: '三', romaji: 'san', meaning: 'three', frequency: 14, example: '三つ (みっつ) - three things' },
        { char: '時', romaji: 'ji/toki', meaning: 'time, hour', frequency: 15, example: '時間 (じかん) - time' },
        { char: '行', romaji: 'kou/iku', meaning: 'to go, conduct', frequency: 16, example: '行く (いく) - to go' },
        { char: '見', romaji: 'ken/miru', meaning: 'to see, to look', frequency: 17, example: '見る (みる) - to see' },
        { char: '月', romaji: 'getsu/tsuki', meaning: 'moon, month', frequency: 18, example: '月 (つき) - moon' },
        { char: '分', romaji: 'bun/fun/wakeru', meaning: 'minute, to divide', frequency: 19, example: '分かる (わかる) - to understand' },
        { char: '後', romaji: 'go/ato', meaning: 'after, behind', frequency: 20, example: '後で (あとで) - later' },
        { char: '前', romaji: 'zen/mae', meaning: 'before, front', frequency: 21, example: '前 (まえ) - front' },
        { char: '生', romaji: 'sei/ikiru', meaning: 'life, to live', frequency: 22, example: '生きる (いきる) - to live' },
        { char: '五', romaji: 'go', meaning: 'five', frequency: 23, example: '五つ (いつつ) - five things' },
        { char: '間', romaji: 'kan/aida', meaning: 'interval, between', frequency: 24, example: '時間 (じかん) - time' },
        { char: '上', romaji: 'jou/ue', meaning: 'up, above', frequency: 25, example: '上 (うえ) - above' },
        { char: '東', romaji: 'tou/higashi', meaning: 'east', frequency: 26, example: '東京 (とうきょう) - Tokyo' },
        { char: '四', romaji: 'shi/yon', meaning: 'four', frequency: 27, example: '四つ (よっつ) - four things' },
        { char: '今', romaji: 'kon/ima', meaning: 'now, present', frequency: 28, example: '今 (いま) - now' },
        { char: '金', romaji: 'kin/kane', meaning: 'gold, money', frequency: 29, example: 'お金 (おかね) - money' },
        { char: '九', romaji: 'kyuu/ku', meaning: 'nine', frequency: 30, example: '九つ (ここのつ) - nine things' },
        { char: '入', romaji: 'nyuu/hairu', meaning: 'enter, to go in', frequency: 31, example: '入る (はいる) - to enter' },
        { char: '学', romaji: 'gaku/manabu', meaning: 'study, learning', frequency: 32, example: '学校 (がっこう) - school' },
        { char: '高', romaji: 'kou/takai', meaning: 'high, expensive', frequency: 33, example: '高い (たかい) - high' },
        { char: '円', romaji: 'en', meaning: 'yen, circle', frequency: 34, example: '円 (えん) - yen' },
        { char: '子', romaji: 'shi/ko', meaning: 'child', frequency: 35, example: '子供 (こども) - child' },
        { char: '外', romaji: 'gai/soto', meaning: 'outside, foreign', frequency: 36, example: '外 (そと) - outside' },
        { char: '八', romaji: 'hachi', meaning: 'eight', frequency: 37, example: '八つ (やっつ) - eight things' },
        { char: '六', romaji: 'roku', meaning: 'six', frequency: 38, example: '六つ (むっつ) - six things' },
        { char: '下', romaji: 'ka/shita', meaning: 'below, under', frequency: 39, example: '下 (した) - below' },
        { char: '来', romaji: 'rai/kuru', meaning: 'to come, next', frequency: 40, example: '来る (くる) - to come' },
        { char: '気', romaji: 'ki/ke', meaning: 'spirit, energy', frequency: 41, example: '元気 (げんき) - healthy' },
        { char: '小', romaji: 'shou/chiisai', meaning: 'small, little', frequency: 42, example: '小さい (ちいさい) - small' },
        { char: '七', romaji: 'shichi/nana', meaning: 'seven', frequency: 43, example: '七つ (ななつ) - seven things' },
        { char: '山', romaji: 'san/yama', meaning: 'mountain', frequency: 44, example: '山 (やま) - mountain' },
        { char: '話', romaji: 'wa/hanasu', meaning: 'talk, story', frequency: 45, example: '話す (はなす) - to speak' },
        { char: '女', romaji: 'jo/onna', meaning: 'woman, female', frequency: 46, example: '女性 (じょせい) - woman' },
        { char: '北', romaji: 'hoku/kita', meaning: 'north', frequency: 47, example: '北 (きた) - north' },
        { char: '午', romaji: 'go', meaning: 'noon', frequency: 48, example: '午前 (ごぜん) - morning' },
        { char: '百', romaji: 'hyaku', meaning: 'hundred', frequency: 49, example: '百 (ひゃく) - hundred' },
        { char: '書', romaji: 'sho/kaku', meaning: 'to write', frequency: 50, example: '書く (かく) - to write' }
    ],

    words: [
        // Common Japanese words
        { char: 'こんにちは', romaji: 'konnichiwa', meaning: 'hello, good afternoon', frequency: 1, example: 'こんにちは！お元気ですか？ - Hello! How are you?' },
        { char: 'ありがとう', romaji: 'arigatou', meaning: 'thank you', frequency: 2, example: 'ありがとうございます - Thank you very much' },
        { char: 'さようなら', romaji: 'sayounara', meaning: 'goodbye', frequency: 3, example: 'さようなら、また明日 - Goodbye, see you tomorrow' },
        { char: 'おはよう', romaji: 'ohayou', meaning: 'good morning', frequency: 4, example: 'おはようございます - Good morning (formal)' },
        { char: 'すみません', romaji: 'sumimasen', meaning: 'excuse me, sorry', frequency: 5, example: 'すみません、お願いします - Excuse me, please' },
        { char: 'はい', romaji: 'hai', meaning: 'yes', frequency: 6, example: 'はい、分かりました - Yes, I understand' },
        { char: 'いいえ', romaji: 'iie', meaning: 'no', frequency: 7, example: 'いいえ、違います - No, that\'s wrong' },
        { char: '食べる', romaji: 'taberu', meaning: 'to eat', frequency: 8, example: '朝ごはんを食べます - I eat breakfast' },
        { char: '飲む', romaji: 'nomu', meaning: 'to drink', frequency: 9, example: '水を飲みます - I drink water' },
        { char: '行く', romaji: 'iku', meaning: 'to go', frequency: 10, example: '学校に行きます - I go to school' },
        { char: '来る', romaji: 'kuru', meaning: 'to come', frequency: 11, example: '明日来ます - I will come tomorrow' },
        { char: '見る', romaji: 'miru', meaning: 'to see, to watch', frequency: 12, example: 'テレビを見ます - I watch TV' },
        { char: '聞く', romaji: 'kiku', meaning: 'to hear, to listen', frequency: 13, example: '音楽を聞きます - I listen to music' },
        { char: '話す', romaji: 'hanasu', meaning: 'to speak', frequency: 14, example: '日本語を話します - I speak Japanese' },
        { char: '読む', romaji: 'yomu', meaning: 'to read', frequency: 15, example: '本を読みます - I read books' },
        { char: '書く', romaji: 'kaku', meaning: 'to write', frequency: 16, example: '手紙を書きます - I write a letter' },
        { char: '勉強', romaji: 'benkyou', meaning: 'study', frequency: 17, example: '日本語を勉強します - I study Japanese' },
        { char: '仕事', romaji: 'shigoto', meaning: 'work, job', frequency: 18, example: '今日は仕事があります - I have work today' },
        { char: '学校', romaji: 'gakkou', meaning: 'school', frequency: 19, example: '学校は楽しいです - School is fun' },
        { char: '先生', romaji: 'sensei', meaning: 'teacher', frequency: 20, example: '先生は優しいです - The teacher is kind' }
    ],

    sentences: [
        // Common Japanese sentences
        { char: 'こんにちは、お元気ですか？', romaji: 'konnichiwa, ogenki desu ka?', meaning: 'Hello, how are you?', frequency: 1, example: 'Basic greeting' },
        { char: '私は学生です。', romaji: 'watashi wa gakusei desu', meaning: 'I am a student', frequency: 2, example: 'Basic self-introduction' },
        { char: 'これは何ですか？', romaji: 'kore wa nan desu ka?', meaning: 'What is this?', frequency: 3, example: 'Asking about objects' },
        { char: 'どこに行きますか？', romaji: 'doko ni ikimasu ka?', meaning: 'Where are you going?', frequency: 4, example: 'Asking about destination' },
        { char: '日本語を勉強しています。', romaji: 'nihongo wo benkyou shiteimasu', meaning: 'I am studying Japanese', frequency: 5, example: 'Talking about activities' },
        { char: '今日はいい天気ですね。', romaji: 'kyou wa ii tenki desu ne', meaning: 'Nice weather today, isn\'t it?', frequency: 6, example: 'Small talk' },
        { char: '分かりません。', romaji: 'wakarimasen', meaning: 'I don\'t understand', frequency: 7, example: 'Expressing confusion' },
        { char: 'もう一度お願いします。', romaji: 'mou ichido onegaishimasu', meaning: 'One more time please', frequency: 8, example: 'Asking for repetition' },
        { char: 'お腹が空きました。', romaji: 'onaka ga sukimashita', meaning: 'I\'m hungry', frequency: 9, example: 'Expressing needs' },
        { char: '何時ですか？', romaji: 'nanji desu ka?', meaning: 'What time is it?', frequency: 10, example: 'Asking for time' }
    ]
};

const frenchData = {
    characters: [
        // Basic French alphabet + accented characters
        { char: 'a', romaji: 'a', meaning: 'letter a', frequency: 1 },
        { char: 'b', romaji: 'b', meaning: 'letter b', frequency: 2 },
        { char: 'c', romaji: 'c', meaning: 'letter c', frequency: 3 },
        { char: 'd', romaji: 'd', meaning: 'letter d', frequency: 4 },
        { char: 'e', romaji: 'e', meaning: 'letter e', frequency: 5 },
        { char: 'f', romaji: 'f', meaning: 'letter f', frequency: 6 },
        { char: 'g', romaji: 'g', meaning: 'letter g', frequency: 7 },
        { char: 'h', romaji: 'h', meaning: 'letter h', frequency: 8 },
        { char: 'i', romaji: 'i', meaning: 'letter i', frequency: 9 },
        { char: 'j', romaji: 'j', meaning: 'letter j', frequency: 10 },
        { char: 'k', romaji: 'k', meaning: 'letter k', frequency: 11 },
        { char: 'l', romaji: 'l', meaning: 'letter l', frequency: 12 },
        { char: 'm', romaji: 'm', meaning: 'letter m', frequency: 13 },
        { char: 'n', romaji: 'n', meaning: 'letter n', frequency: 14 },
        { char: 'o', romaji: 'o', meaning: 'letter o', frequency: 15 },
        { char: 'p', romaji: 'p', meaning: 'letter p', frequency: 16 },
        { char: 'q', romaji: 'q', meaning: 'letter q', frequency: 17 },
        { char: 'r', romaji: 'r', meaning: 'letter r', frequency: 18 },
        { char: 's', romaji: 's', meaning: 'letter s', frequency: 19 },
        { char: 't', romaji: 't', meaning: 'letter t', frequency: 20 },
        { char: 'u', romaji: 'u', meaning: 'letter u', frequency: 21 },
        { char: 'v', romaji: 'v', meaning: 'letter v', frequency: 22 },
        { char: 'w', romaji: 'w', meaning: 'letter w', frequency: 23 },
        { char: 'x', romaji: 'x', meaning: 'letter x', frequency: 24 },
        { char: 'y', romaji: 'y', meaning: 'letter y', frequency: 25 },
        { char: 'z', romaji: 'z', meaning: 'letter z', frequency: 26 },
        // Accented characters
        { char: 'é', romaji: 'é (e acute)', meaning: 'accented e', frequency: 27, example: 'café, été' },
        { char: 'è', romaji: 'è (e grave)', meaning: 'accented e', frequency: 28, example: 'père, mère' },
        { char: 'ê', romaji: 'ê (e circumflex)', meaning: 'accented e', frequency: 29, example: 'être, fête' },
        { char: 'ë', romaji: 'ë (e diaeresis)', meaning: 'accented e', frequency: 30, example: 'Noël' },
        { char: 'à', romaji: 'à (a grave)', meaning: 'accented a', frequency: 31, example: 'à, voilà' },
        { char: 'â', romaji: 'â (a circumflex)', meaning: 'accented a', frequency: 32, example: 'pâte' },
        { char: 'ù', romaji: 'ù (u grave)', meaning: 'accented u', frequency: 33, example: 'où' },
        { char: 'û', romaji: 'û (u circumflex)', meaning: 'accented u', frequency: 34, example: 'sûr' },
        { char: 'ô', romaji: 'ô (o circumflex)', meaning: 'accented o', frequency: 35, example: 'hôtel' },
        { char: 'î', romaji: 'î (i circumflex)', meaning: 'accented i', frequency: 36, example: 'île' },
        { char: 'ï', romaji: 'ï (i diaeresis)', meaning: 'accented i', frequency: 37, example: 'maïs' },
        { char: 'ç', romaji: 'ç (c cedilla)', meaning: 'c with cedilla', frequency: 38, example: 'français, garçon' },
        { char: 'œ', romaji: 'œ (oe ligature)', meaning: 'oe ligature', frequency: 39, example: 'cœur, sœur' },
        { char: 'æ', romaji: 'æ (ae ligature)', meaning: 'ae ligature', frequency: 40, example: 'ex æquo' }
    ],

    words: [
        { char: 'bonjour', romaji: 'bon-zhoor', meaning: 'hello, good day', frequency: 1, example: 'Bonjour! Comment allez-vous?' },
        { char: 'merci', romaji: 'mehr-see', meaning: 'thank you', frequency: 2, example: 'Merci beaucoup!' },
        { char: 'au revoir', romaji: 'oh ruh-vwahr', meaning: 'goodbye', frequency: 3, example: 'Au revoir, à bientôt!' },
        { char: 's\'il vous plaît', romaji: 'seel voo pleh', meaning: 'please', frequency: 4, example: 'S\'il vous plaît, aidez-moi' },
        { char: 'oui', romaji: 'wee', meaning: 'yes', frequency: 5, example: 'Oui, c\'est vrai' },
        { char: 'non', romaji: 'nohn', meaning: 'no', frequency: 6, example: 'Non, ce n\'est pas correct' },
        { char: 'pardon', romaji: 'par-dohn', meaning: 'excuse me, sorry', frequency: 7, example: 'Pardon, je ne comprends pas' },
        { char: 'je', romaji: 'zhuh', meaning: 'I', frequency: 8, example: 'Je suis étudiant' },
        { char: 'tu', romaji: 'too', meaning: 'you (informal)', frequency: 9, example: 'Tu es français?' },
        { char: 'il/elle', romaji: 'eel/ell', meaning: 'he/she', frequency: 10, example: 'Il est ici' },
        { char: 'nous', romaji: 'noo', meaning: 'we', frequency: 11, example: 'Nous allons à Paris' },
        { char: 'vous', romaji: 'voo', meaning: 'you (formal/plural)', frequency: 12, example: 'Vous êtes très gentil' },
        { char: 'être', romaji: 'eh-truh', meaning: 'to be', frequency: 13, example: 'Je suis, tu es, il est' },
        { char: 'avoir', romaji: 'ah-vwahr', meaning: 'to have', frequency: 14, example: 'J\'ai, tu as, il a' },
        { char: 'aller', romaji: 'ah-lay', meaning: 'to go', frequency: 15, example: 'Je vais à l\'école' },
        { char: 'faire', romaji: 'fehr', meaning: 'to do, to make', frequency: 16, example: 'Je fais mes devoirs' },
        { char: 'manger', romaji: 'mahn-zhay', meaning: 'to eat', frequency: 17, example: 'Je mange du pain' },
        { char: 'boire', romaji: 'bwahr', meaning: 'to drink', frequency: 18, example: 'Je bois de l\'eau' },
        { char: 'parler', romaji: 'par-lay', meaning: 'to speak', frequency: 19, example: 'Je parle français' },
        { char: 'comprendre', romaji: 'kohm-prahn-druh', meaning: 'to understand', frequency: 20, example: 'Je comprends maintenant' }
    ],

    sentences: [
        { char: 'Comment allez-vous?', romaji: 'koh-mahn tah-lay voo', meaning: 'How are you?', frequency: 1, example: 'Formal greeting' },
        { char: 'Je m\'appelle...', romaji: 'zhuh mah-pell', meaning: 'My name is...', frequency: 2, example: 'Self-introduction' },
        { char: 'Où sont les toilettes?', romaji: 'oo sohn lay twah-let', meaning: 'Where is the bathroom?', frequency: 3, example: 'Asking for directions' },
        { char: 'Je ne comprends pas', romaji: 'zhuh nuh kohm-prahn pah', meaning: 'I don\'t understand', frequency: 4, example: 'Expressing confusion' },
        { char: 'Parlez-vous anglais?', romaji: 'par-lay voo ahn-gleh', meaning: 'Do you speak English?', frequency: 5, example: 'Language question' },
        { char: 'Combien ça coûte?', romaji: 'kohm-byahn sah koot', meaning: 'How much does it cost?', frequency: 6, example: 'Shopping' },
        { char: 'J\'ai faim', romaji: 'zhay fahm', meaning: 'I\'m hungry', frequency: 7, example: 'Expressing need' },
        { char: 'Quelle heure est-il?', romaji: 'kell uhr eh-teel', meaning: 'What time is it?', frequency: 8, example: 'Asking for time' },
        { char: 'Je voudrais...', romaji: 'zhuh voo-dreh', meaning: 'I would like...', frequency: 9, example: 'Polite request' },
        { char: 'Pouvez-vous m\'aider?', romaji: 'poo-vay voo may-day', meaning: 'Can you help me?', frequency: 10, example: 'Asking for help' }
    ]
};

const gujaratiData = {
    characters: [
        // Gujarati vowels (સ્વર)
        { char: 'અ', romaji: 'a', meaning: 'vowel a', frequency: 1, example: 'અ as in અમે (ame - we)' },
        { char: 'આ', romaji: 'ā', meaning: 'vowel ā', frequency: 2, example: 'આ as in આપ (āp - you)' },
        { char: 'ઇ', romaji: 'i', meaning: 'vowel i', frequency: 3, example: 'ઇ as in ઇચ્છા (icchā - wish)' },
        { char: 'ઈ', romaji: 'ī', meaning: 'vowel ī', frequency: 4, example: 'ઈ as in ઈશ્વર (īśvar - god)' },
        { char: 'ઉ', romaji: 'u', meaning: 'vowel u', frequency: 5, example: 'ઉ as in ઉત્તર (uttar - north)' },
        { char: 'ઊ', romaji: 'ū', meaning: 'vowel ū', frequency: 6, example: 'ઊ as in ઊંચું (ūṃcuṃ - tall)' },
        { char: 'એ', romaji: 'e', meaning: 'vowel e', frequency: 7, example: 'એ as in એક (ek - one)' },
        { char: 'ઐ', romaji: 'ai', meaning: 'vowel ai', frequency: 8, example: 'ઐ as in ઐશ્વર્ય (aiśvarya - wealth)' },
        { char: 'ઓ', romaji: 'o', meaning: 'vowel o', frequency: 9, example: 'ઓ as in ઓળખ (oḷakh - identity)' },
        { char: 'ઔ', romaji: 'au', meaning: 'vowel au', frequency: 10, example: 'ઔ as in ઔષધ (auṣadh - medicine)' },
        // Gujarati consonants (વ્યંજન)
        { char: 'ક', romaji: 'ka', meaning: 'consonant ka', frequency: 11, example: 'ક as in કમળ (kamaḷ - lotus)' },
        { char: 'ખ', romaji: 'kha', meaning: 'consonant kha', frequency: 12, example: 'ખ as in ખુશી (khushī - happiness)' },
        { char: 'ગ', romaji: 'ga', meaning: 'consonant ga', frequency: 13, example: 'ગ as in ગામ (gām - village)' },
        { char: 'ઘ', romaji: 'gha', meaning: 'consonant gha', frequency: 14, example: 'ઘ as in ઘર (ghar - house)' },
        { char: 'ચ', romaji: 'ca', meaning: 'consonant ca', frequency: 15, example: 'ચ as in ચા (cā - tea)' },
        { char: 'છ', romaji: 'cha', meaning: 'consonant cha', frequency: 16, example: 'છ as in છોકરો (chokaro - boy)' },
        { char: 'જ', romaji: 'ja', meaning: 'consonant ja', frequency: 17, example: 'જ as in જળ (jaḷ - water)' },
        { char: 'ઝ', romaji: 'jha', meaning: 'consonant jha', frequency: 18, example: 'ઝ as in ઝાડ (jhāḍ - tree)' },
        { char: 'ટ', romaji: 'ṭa', meaning: 'consonant ṭa', frequency: 19, example: 'ટ as in ટોપી (ṭopī - hat)' },
        { char: 'ઠ', romaji: 'ṭha', meaning: 'consonant ṭha', frequency: 20, example: 'ઠ as in ઠંડી (ṭhaṇḍī - cold)' },
        { char: 'ડ', romaji: 'ḍa', meaning: 'consonant ḍa', frequency: 21, example: 'ડ as in ડબ્બો (ḍabbo - box)' },
        { char: 'ઢ', romaji: 'ḍha', meaning: 'consonant ḍha', frequency: 22, example: 'ઢ as in ઢોલ (ḍhol - drum)' },
        { char: 'ણ', romaji: 'ṇa', meaning: 'consonant ṇa', frequency: 23, example: 'ણ as in જાણવું (jāṇavuṃ - to know)' },
        { char: 'ત', romaji: 'ta', meaning: 'consonant ta', frequency: 24, example: 'ત as in તમે (tame - you)' },
        { char: 'થ', romaji: 'tha', meaning: 'consonant tha', frequency: 25, example: 'થ as in થાળી (thāḷī - plate)' },
        { char: 'દ', romaji: 'da', meaning: 'consonant da', frequency: 26, example: 'દ as in દિવસ (divas - day)' },
        { char: 'ધ', romaji: 'dha', meaning: 'consonant dha', frequency: 27, example: 'ધ as in ધન (dhan - wealth)' },
        { char: 'ન', romaji: 'na', meaning: 'consonant na', frequency: 28, example: 'ન as in નામ (nām - name)' },
        { char: 'પ', romaji: 'pa', meaning: 'consonant pa', frequency: 29, example: 'પ as in પાણી (pāṇī - water)' },
        { char: 'ફ', romaji: 'pha', meaning: 'consonant pha', frequency: 30, example: 'ફ as in ફૂલ (phūl - flower)' },
        { char: 'બ', romaji: 'ba', meaning: 'consonant ba', frequency: 31, example: 'બ as in બાળક (bāḷak - child)' },
        { char: 'ભ', romaji: 'bha', meaning: 'consonant bha', frequency: 32, example: 'ભ as in ભાષા (bhāṣā - language)' },
        { char: 'મ', romaji: 'ma', meaning: 'consonant ma', frequency: 33, example: 'મ as in માતા (mātā - mother)' },
        { char: 'ય', romaji: 'ya', meaning: 'consonant ya', frequency: 34, example: 'ય as in યુવા (yuvā - youth)' },
        { char: 'ર', romaji: 'ra', meaning: 'consonant ra', frequency: 35, example: 'ર as in રાત (rāt - night)' },
        { char: 'લ', romaji: 'la', meaning: 'consonant la', frequency: 36, example: 'લ as in લાલ (lāl - red)' },
        { char: 'વ', romaji: 'va', meaning: 'consonant va', frequency: 37, example: 'વ as in વાત (vāt - talk)' },
        { char: 'શ', romaji: 'śa', meaning: 'consonant śa', frequency: 38, example: 'શ as in શાળા (śāḷā - school)' },
        { char: 'ષ', romaji: 'ṣa', meaning: 'consonant ṣa', frequency: 39, example: 'ષ as in ષડયંત્ર (ṣaḍyantra - conspiracy)' },
        { char: 'સ', romaji: 'sa', meaning: 'consonant sa', frequency: 40, example: 'સ as in સત્ય (satya - truth)' },
        { char: 'હ', romaji: 'ha', meaning: 'consonant ha', frequency: 41, example: 'હ as in હા (hā - yes)' }
    ],

    words: [
        { char: 'નમસ્તે', romaji: 'namaste', meaning: 'hello, greetings', frequency: 1, example: 'નમસ્તે! તમે કેમ છો?' },
        { char: 'આભાર', romaji: 'ābhār', meaning: 'thank you', frequency: 2, example: 'તમારો આભાર' },
        { char: 'હા', romaji: 'hā', meaning: 'yes', frequency: 3, example: 'હા, બરાબર છે' },
        { char: 'ના', romaji: 'nā', meaning: 'no', frequency: 4, example: 'ના, તે યોગ્ય નથી' },
        { char: 'માફ કરશો', romaji: 'māf karśo', meaning: 'sorry, excuse me', frequency: 5, example: 'માફ કરશો, હું સમજ્યો નહીં' },
        { char: 'પાણી', romaji: 'pāṇī', meaning: 'water', frequency: 6, example: 'મને પાણી જોઈએ' },
        { char: 'ખાવું', romaji: 'khāvuṃ', meaning: 'to eat', frequency: 7, example: 'હું રોટલી ખાઉં છું' },
        { char: 'પીવું', romaji: 'pīvuṃ', meaning: 'to drink', frequency: 8, example: 'હું ચા પીઉં છું' },
        { char: 'જવું', romaji: 'javuṃ', meaning: 'to go', frequency: 9, example: 'હું શાળાએ જાઉં છું' },
        { char: 'આવવું', romaji: 'āvavuṃ', meaning: 'to come', frequency: 10, example: 'તમે આવો' },
        { char: 'બોલવું', romaji: 'bolavuṃ', meaning: 'to speak', frequency: 11, example: 'હું ગુજરાતી બોલું છું' },
        { char: 'વાંચવું', romaji: 'vāṃcavuṃ', meaning: 'to read', frequency: 12, example: 'હું પુસ્તક વાંચું છું' },
        { char: 'લખવું', romaji: 'lakhavuṃ', meaning: 'to write', frequency: 13, example: 'હું પત્ર લખું છું' },
        { char: 'સમજવું', romaji: 'samajavuṃ', meaning: 'to understand', frequency: 14, example: 'હવે હું સમજ્યો' },
        { char: 'શીખવું', romaji: 'śīkhavuṃ', meaning: 'to learn', frequency: 15, example: 'હું ગુજરાતી શીખું છું' },
        { char: 'ઘર', romaji: 'ghar', meaning: 'house, home', frequency: 16, example: 'આ મારું ઘર છે' },
        { char: 'શાળા', romaji: 'śāḷā', meaning: 'school', frequency: 17, example: 'બાળકો શાળામાં જાય છે' },
        { char: 'મિત્ર', romaji: 'mitra', meaning: 'friend', frequency: 18, example: 'તે મારો મિત્ર છે' },
        { char: 'કુટુંબ', romaji: 'kuṭuṃba', meaning: 'family', frequency: 19, example: 'મારું કુટુંબ મોટું છે' },
        { char: 'પ્રેમ', romaji: 'prem', meaning: 'love', frequency: 20, example: 'પ્રેમ મહત્વનું છે' }
    ],

    sentences: [
        { char: 'તમે કેમ છો?', romaji: 'tame kem cho?', meaning: 'How are you?', frequency: 1, example: 'Basic greeting' },
        { char: 'મારું નામ... છે', romaji: 'māruṃ nām... che', meaning: 'My name is...', frequency: 2, example: 'Self-introduction' },
        { char: 'હું ગુજરાતી શીખું છું', romaji: 'huṃ gujarātī śīkhuṃ chuṃ', meaning: 'I am learning Gujarati', frequency: 3, example: 'Talking about learning' },
        { char: 'તમે ક્યાંથી આવો છો?', romaji: 'tame kyāṃthī āvo cho?', meaning: 'Where are you from?', frequency: 4, example: 'Asking about origin' },
        { char: 'મને સમજાયું નહીં', romaji: 'mane samajāyuṃ nahīṃ', meaning: 'I didn\'t understand', frequency: 5, example: 'Expressing confusion' },
        { char: 'આ કેટલું છે?', romaji: 'ā keṭaluṃ che?', meaning: 'How much is this?', frequency: 6, example: 'Shopping' },
        { char: 'મને ભૂખ લાગી છે', romaji: 'mane bhūkh lāgī che', meaning: 'I am hungry', frequency: 7, example: 'Expressing need' },
        { char: 'સમય શું થયો?', romaji: 'samay śuṃ thayo?', meaning: 'What time is it?', frequency: 8, example: 'Asking for time' },
        { char: 'કૃપા કરીને મને મદદ કરો', romaji: 'kṛpā karīne mane madad karo', meaning: 'Please help me', frequency: 9, example: 'Asking for help' },
        { char: 'તમારો દિવસ શુભ હો', romaji: 'tamāro divas śubh ho', meaning: 'Have a good day', frequency: 10, example: 'Well-wishing' }
    ]
};

// Unified data structure
const languageData = {
    japanese: japaneseData,
    french: frenchData,
    gujarati: gujaratiData
};
