// Japanese Learning Data
// Frequency-based data for spaced repetition learning

const japaneseData = {
    hiragana: [
        // Basic 46 characters (by frequency)
        { char: 'あ', romaji: 'a', meaning: 'a sound', frequency: 1 },
        { char: 'い', romaji: 'i', meaning: 'i sound', frequency: 2 },
        { char: 'う', romaji: 'u', meaning: 'u sound', frequency: 3 },
        { char: 'え', romaji: 'e', meaning: 'e sound', frequency: 4 },
        { char: 'お', romaji: 'o', meaning: 'o sound', frequency: 5 },
        { char: 'か', romaji: 'ka', meaning: 'ka sound', frequency: 6 },
        { char: 'き', romaji: 'ki', meaning: 'ki sound', frequency: 7 },
        { char: 'く', romaji: 'ku', meaning: 'ku sound', frequency: 8 },
        { char: 'け', romaji: 'ke', meaning: 'ke sound', frequency: 9 },
        { char: 'こ', romaji: 'ko', meaning: 'ko sound', frequency: 10 },
        { char: 'さ', romaji: 'sa', meaning: 'sa sound', frequency: 11 },
        { char: 'し', romaji: 'shi', meaning: 'shi sound', frequency: 12 },
        { char: 'す', romaji: 'su', meaning: 'su sound', frequency: 13 },
        { char: 'せ', romaji: 'se', meaning: 'se sound', frequency: 14 },
        { char: 'そ', romaji: 'so', meaning: 'so sound', frequency: 15 },
        { char: 'た', romaji: 'ta', meaning: 'ta sound', frequency: 16 },
        { char: 'ち', romaji: 'chi', meaning: 'chi sound', frequency: 17 },
        { char: 'つ', romaji: 'tsu', meaning: 'tsu sound', frequency: 18 },
        { char: 'て', romaji: 'te', meaning: 'te sound', frequency: 19 },
        { char: 'と', romaji: 'to', meaning: 'to sound', frequency: 20 },
        { char: 'な', romaji: 'na', meaning: 'na sound', frequency: 21 },
        { char: 'に', romaji: 'ni', meaning: 'ni sound', frequency: 22 },
        { char: 'ぬ', romaji: 'nu', meaning: 'nu sound', frequency: 23 },
        { char: 'ね', romaji: 'ne', meaning: 'ne sound', frequency: 24 },
        { char: 'の', romaji: 'no', meaning: 'no sound', frequency: 25 },
        { char: 'は', romaji: 'ha', meaning: 'ha sound', frequency: 26 },
        { char: 'ひ', romaji: 'hi', meaning: 'hi sound', frequency: 27 },
        { char: 'ふ', romaji: 'fu', meaning: 'fu sound', frequency: 28 },
        { char: 'へ', romaji: 'he', meaning: 'he sound', frequency: 29 },
        { char: 'ほ', romaji: 'ho', meaning: 'ho sound', frequency: 30 },
        { char: 'ま', romaji: 'ma', meaning: 'ma sound', frequency: 31 },
        { char: 'み', romaji: 'mi', meaning: 'mi sound', frequency: 32 },
        { char: 'む', romaji: 'mu', meaning: 'mu sound', frequency: 33 },
        { char: 'め', romaji: 'me', meaning: 'me sound', frequency: 34 },
        { char: 'も', romaji: 'mo', meaning: 'mo sound', frequency: 35 },
        { char: 'や', romaji: 'ya', meaning: 'ya sound', frequency: 36 },
        { char: 'ゆ', romaji: 'yu', meaning: 'yu sound', frequency: 37 },
        { char: 'よ', romaji: 'yo', meaning: 'yo sound', frequency: 38 },
        { char: 'ら', romaji: 'ra', meaning: 'ra sound', frequency: 39 },
        { char: 'り', romaji: 'ri', meaning: 'ri sound', frequency: 40 },
        { char: 'る', romaji: 'ru', meaning: 'ru sound', frequency: 41 },
        { char: 'れ', romaji: 're', meaning: 're sound', frequency: 42 },
        { char: 'ろ', romaji: 'ro', meaning: 'ro sound', frequency: 43 },
        { char: 'わ', romaji: 'wa', meaning: 'wa sound', frequency: 44 },
        { char: 'を', romaji: 'wo', meaning: 'wo particle', frequency: 45 },
        { char: 'ん', romaji: 'n', meaning: 'n sound', frequency: 46 }
    ],

    katakana: [
        // Basic 46 characters
        { char: 'ア', romaji: 'a', meaning: 'a sound', frequency: 1 },
        { char: 'イ', romaji: 'i', meaning: 'i sound', frequency: 2 },
        { char: 'ウ', romaji: 'u', meaning: 'u sound', frequency: 3 },
        { char: 'エ', romaji: 'e', meaning: 'e sound', frequency: 4 },
        { char: 'オ', romaji: 'o', meaning: 'o sound', frequency: 5 },
        { char: 'カ', romaji: 'ka', meaning: 'ka sound', frequency: 6 },
        { char: 'キ', romaji: 'ki', meaning: 'ki sound', frequency: 7 },
        { char: 'ク', romaji: 'ku', meaning: 'ku sound', frequency: 8 },
        { char: 'ケ', romaji: 'ke', meaning: 'ke sound', frequency: 9 },
        { char: 'コ', romaji: 'ko', meaning: 'ko sound', frequency: 10 },
        { char: 'サ', romaji: 'sa', meaning: 'sa sound', frequency: 11 },
        { char: 'シ', romaji: 'shi', meaning: 'shi sound', frequency: 12 },
        { char: 'ス', romaji: 'su', meaning: 'su sound', frequency: 13 },
        { char: 'セ', romaji: 'se', meaning: 'se sound', frequency: 14 },
        { char: 'ソ', romaji: 'so', meaning: 'so sound', frequency: 15 },
        { char: 'タ', romaji: 'ta', meaning: 'ta sound', frequency: 16 },
        { char: 'チ', romaji: 'chi', meaning: 'chi sound', frequency: 17 },
        { char: 'ツ', romaji: 'tsu', meaning: 'tsu sound', frequency: 18 },
        { char: 'テ', romaji: 'te', meaning: 'te sound', frequency: 19 },
        { char: 'ト', romaji: 'to', meaning: 'to sound', frequency: 20 },
        { char: 'ナ', romaji: 'na', meaning: 'na sound', frequency: 21 },
        { char: 'ニ', romaji: 'ni', meaning: 'ni sound', frequency: 22 },
        { char: 'ヌ', romaji: 'nu', meaning: 'nu sound', frequency: 23 },
        { char: 'ネ', romaji: 'ne', meaning: 'ne sound', frequency: 24 },
        { char: 'ノ', romaji: 'no', meaning: 'no sound', frequency: 25 },
        { char: 'ハ', romaji: 'ha', meaning: 'ha sound', frequency: 26 },
        { char: 'ヒ', romaji: 'hi', meaning: 'hi sound', frequency: 27 },
        { char: 'フ', romaji: 'fu', meaning: 'fu sound', frequency: 28 },
        { char: 'ヘ', romaji: 'he', meaning: 'he sound', frequency: 29 },
        { char: 'ホ', romaji: 'ho', meaning: 'ho sound', frequency: 30 },
        { char: 'マ', romaji: 'ma', meaning: 'ma sound', frequency: 31 },
        { char: 'ミ', romaji: 'mi', meaning: 'mi sound', frequency: 32 },
        { char: 'ム', romaji: 'mu', meaning: 'mu sound', frequency: 33 },
        { char: 'メ', romaji: 'me', meaning: 'me sound', frequency: 34 },
        { char: 'モ', romaji: 'mo', meaning: 'mo sound', frequency: 35 },
        { char: 'ヤ', romaji: 'ya', meaning: 'ya sound', frequency: 36 },
        { char: 'ユ', romaji: 'yu', meaning: 'yu sound', frequency: 37 },
        { char: 'ヨ', romaji: 'yo', meaning: 'yo sound', frequency: 38 },
        { char: 'ラ', romaji: 'ra', meaning: 'ra sound', frequency: 39 },
        { char: 'リ', romaji: 'ri', meaning: 'ri sound', frequency: 40 },
        { char: 'ル', romaji: 'ru', meaning: 'ru sound', frequency: 41 },
        { char: 'レ', romaji: 're', meaning: 're sound', frequency: 42 },
        { char: 'ロ', romaji: 'ro', meaning: 'ro sound', frequency: 43 },
        { char: 'ワ', romaji: 'wa', meaning: 'wa sound', frequency: 44 },
        { char: 'ヲ', romaji: 'wo', meaning: 'wo particle', frequency: 45 },
        { char: 'ン', romaji: 'n', meaning: 'n sound', frequency: 46 }
    ],

    kanji: [
        // Most common kanji (JLPT N5 and high frequency)
        { char: '人', romaji: 'hito/jin', meaning: 'person, human', frequency: 1, example: '人 (ひと) - person' },
        { char: '日', romaji: 'hi/nichi', meaning: 'day, sun', frequency: 2, example: '今日 (きょう) - today' },
        { char: '一', romaji: 'ichi', meaning: 'one', frequency: 3, example: '一つ (ひとつ) - one thing' },
        { char: '国', romaji: 'kuni/koku', meaning: 'country', frequency: 4, example: '国 (くに) - country' },
        { char: '会', romaji: 'kai', meaning: 'meeting, association', frequency: 5, example: '会う (あう) - to meet' },
        { char: '年', romaji: 'nen/toshi', meaning: 'year', frequency: 6, example: '今年 (ことし) - this year' },
        { char: '大', romaji: 'dai/oo', meaning: 'big, large', frequency: 7, example: '大きい (おおきい) - big' },
        { char: '十', romaji: 'juu', meaning: 'ten', frequency: 8, example: '十 (じゅう) - ten' },
        { char: '二', romaji: 'ni', meaning: 'two', frequency: 9, example: '二つ (ふたつ) - two things' },
        { char: '本', romaji: 'hon/moto', meaning: 'book, origin', frequency: 10, example: '本 (ほん) - book' },
        { char: '中', romaji: 'chuu/naka', meaning: 'middle, inside', frequency: 11, example: '中 (なか) - inside' },
        { char: '長', romaji: 'chou/nagai', meaning: 'long, chief', frequency: 12, example: '長い (ながい) - long' },
        { char: '出', romaji: 'shutsu/deru', meaning: 'exit, to go out', frequency: 13, example: '出る (でる) - to exit' },
        { char: '三', romaji: 'san', meaning: 'three', frequency: 14, example: '三つ (みっつ) - three things' },
        { char: '時', romaji: 'ji/toki', meaning: 'time, hour', frequency: 15, example: '時間 (じかん) - time' },
        { char: '行', romaji: 'kou/iku', meaning: 'to go, conduct', frequency: 16, example: '行く (いく) - to go' },
        { char: '見', romaji: 'ken/miru', meaning: 'to see, to look', frequency: 17, example: '見る (みる) - to see' },
        { char: '月', romaji: 'getsu/tsuki', meaning: 'moon, month', frequency: 18, example: '月 (つき) - moon' },
        { char: '分', romaji: 'bun/fun/wakeru', meaning: 'minute, to divide', frequency: 19, example: '分かる (わかる) - to understand' },
        { char: '後', romaji: 'go/ato', meaning: 'after, behind', frequency: 20, example: '後で (あとで) - later' },
        { char: '前', romaji: 'zen/mae', meaning: 'before, front', frequency: 21, example: '前 (まえ) - front' },
        { char: '生', romaji: 'sei/ikiru', meaning: 'life, to live', frequency: 22, example: '生きる (いきる) - to live' },
        { char: '五', romaji: 'go', meaning: 'five', frequency: 23, example: '五つ (いつつ) - five things' },
        { char: '間', romaji: 'kan/aida', meaning: 'interval, between', frequency: 24, example: '時間 (じかん) - time' },
        { char: '上', romaji: 'jou/ue', meaning: 'up, above', frequency: 25, example: '上 (うえ) - above' },
        { char: '東', romaji: 'tou/higashi', meaning: 'east', frequency: 26, example: '東京 (とうきょう) - Tokyo' },
        { char: '四', romaji: 'shi/yon', meaning: 'four', frequency: 27, example: '四つ (よっつ) - four things' },
        { char: '今', romaji: 'kon/ima', meaning: 'now, present', frequency: 28, example: '今 (いま) - now' },
        { char: '金', romaji: 'kin/kane', meaning: 'gold, money', frequency: 29, example: 'お金 (おかね) - money' },
        { char: '九', romaji: 'kyuu/ku', meaning: 'nine', frequency: 30, example: '九つ (ここのつ) - nine things' },
        { char: '入', romaji: 'nyuu/hairu', meaning: 'enter, to go in', frequency: 31, example: '入る (はいる) - to enter' },
        { char: '学', romaji: 'gaku/manabu', meaning: 'study, learning', frequency: 32, example: '学校 (がっこう) - school' },
        { char: '高', romaji: 'kou/takai', meaning: 'high, expensive', frequency: 33, example: '高い (たかい) - high' },
        { char: '円', romaji: 'en', meaning: 'yen, circle', frequency: 34, example: '円 (えん) - yen' },
        { char: '子', romaji: 'shi/ko', meaning: 'child', frequency: 35, example: '子供 (こども) - child' },
        { char: '外', romaji: 'gai/soto', meaning: 'outside, foreign', frequency: 36, example: '外 (そと) - outside' },
        { char: '八', romaji: 'hachi', meaning: 'eight', frequency: 37, example: '八つ (やっつ) - eight things' },
        { char: '六', romaji: 'roku', meaning: 'six', frequency: 38, example: '六つ (むっつ) - six things' },
        { char: '下', romaji: 'ka/shita', meaning: 'below, under', frequency: 39, example: '下 (した) - below' },
        { char: '来', romaji: 'rai/kuru', meaning: 'to come, next', frequency: 40, example: '来る (くる) - to come' },
        { char: '気', romaji: 'ki/ke', meaning: 'spirit, energy', frequency: 41, example: '元気 (げんき) - healthy' },
        { char: '小', romaji: 'shou/chiisai', meaning: 'small, little', frequency: 42, example: '小さい (ちいさい) - small' },
        { char: '七', romaji: 'shichi/nana', meaning: 'seven', frequency: 43, example: '七つ (ななつ) - seven things' },
        { char: '山', romaji: 'san/yama', meaning: 'mountain', frequency: 44, example: '山 (やま) - mountain' },
        { char: '話', romaji: 'wa/hanasu', meaning: 'talk, story', frequency: 45, example: '話す (はなす) - to speak' },
        { char: '女', romaji: 'jo/onna', meaning: 'woman, female', frequency: 46, example: '女性 (じょせい) - woman' },
        { char: '北', romaji: 'hoku/kita', meaning: 'north', frequency: 47, example: '北 (きた) - north' },
        { char: '午', romaji: 'go', meaning: 'noon', frequency: 48, example: '午前 (ごぜん) - morning' },
        { char: '百', romaji: 'hyaku', meaning: 'hundred', frequency: 49, example: '百 (ひゃく) - hundred' },
        { char: '書', romaji: 'sho/kaku', meaning: 'to write', frequency: 50, example: '書く (かく) - to write' }
    ],

    words: [
        // Common Japanese words
        { char: 'こんにちは', romaji: 'konnichiwa', meaning: 'hello, good afternoon', frequency: 1, example: 'こんにちは！お元気ですか？ - Hello! How are you?' },
        { char: 'ありがとう', romaji: 'arigatou', meaning: 'thank you', frequency: 2, example: 'ありがとうございます - Thank you very much' },
        { char: 'さようなら', romaji: 'sayounara', meaning: 'goodbye', frequency: 3, example: 'さようなら、また明日 - Goodbye, see you tomorrow' },
        { char: 'おはよう', romaji: 'ohayou', meaning: 'good morning', frequency: 4, example: 'おはようございます - Good morning (formal)' },
        { char: 'すみません', romaji: 'sumimasen', meaning: 'excuse me, sorry', frequency: 5, example: 'すみません、お願いします - Excuse me, please' },
        { char: 'はい', romaji: 'hai', meaning: 'yes', frequency: 6, example: 'はい、分かりました - Yes, I understand' },
        { char: 'いいえ', romaji: 'iie', meaning: 'no', frequency: 7, example: 'いいえ、違います - No, that\'s wrong' },
        { char: '食べる', romaji: 'taberu', meaning: 'to eat', frequency: 8, example: '朝ごはんを食べます - I eat breakfast' },
        { char: '飲む', romaji: 'nomu', meaning: 'to drink', frequency: 9, example: '水を飲みます - I drink water' },
        { char: '行く', romaji: 'iku', meaning: 'to go', frequency: 10, example: '学校に行きます - I go to school' },
        { char: '来る', romaji: 'kuru', meaning: 'to come', frequency: 11, example: '明日来ます - I will come tomorrow' },
        { char: '見る', romaji: 'miru', meaning: 'to see, to watch', frequency: 12, example: 'テレビを見ます - I watch TV' },
        { char: '聞く', romaji: 'kiku', meaning: 'to hear, to listen', frequency: 13, example: '音楽を聞きます - I listen to music' },
        { char: '話す', romaji: 'hanasu', meaning: 'to speak', frequency: 14, example: '日本語を話します - I speak Japanese' },
        { char: '読む', romaji: 'yomu', meaning: 'to read', frequency: 15, example: '本を読みます - I read books' },
        { char: '書く', romaji: 'kaku', meaning: 'to write', frequency: 16, example: '手紙を書きます - I write a letter' },
        { char: '勉強', romaji: 'benkyou', meaning: 'study', frequency: 17, example: '日本語を勉強します - I study Japanese' },
        { char: '仕事', romaji: 'shigoto', meaning: 'work, job', frequency: 18, example: '今日は仕事があります - I have work today' },
        { char: '学校', romaji: 'gakkou', meaning: 'school', frequency: 19, example: '学校は楽しいです - School is fun' },
        { char: '先生', romaji: 'sensei', meaning: 'teacher', frequency: 20, example: '先生は優しいです - The teacher is kind' }
    ],

    sentences: [
        // Common Japanese sentences
        { char: 'こんにちは、お元気ですか？', romaji: 'konnichiwa, ogenki desu ka?', meaning: 'Hello, how are you?', frequency: 1, example: 'Basic greeting' },
        { char: '私は学生です。', romaji: 'watashi wa gakusei desu', meaning: 'I am a student', frequency: 2, example: 'Basic self-introduction' },
        { char: 'これは何ですか？', romaji: 'kore wa nan desu ka?', meaning: 'What is this?', frequency: 3, example: 'Asking about objects' },
        { char: 'どこに行きますか？', romaji: 'doko ni ikimasu ka?', meaning: 'Where are you going?', frequency: 4, example: 'Asking about destination' },
        { char: '日本語を勉強しています。', romaji: 'nihongo wo benkyou shiteimasu', meaning: 'I am studying Japanese', frequency: 5, example: 'Talking about activities' },
        { char: '今日はいい天気ですね。', romaji: 'kyou wa ii tenki desu ne', meaning: 'Nice weather today, isn\'t it?', frequency: 6, example: 'Small talk' },
        { char: '分かりません。', romaji: 'wakarimasen', meaning: 'I don\'t understand', frequency: 7, example: 'Expressing confusion' },
        { char: 'もう一度お願いします。', romaji: 'mou ichido onegaishimasu', meaning: 'One more time please', frequency: 8, example: 'Asking for repetition' },
        { char: 'お腹が空きました。', romaji: 'onaka ga sukimashita', meaning: 'I\'m hungry', frequency: 9, example: 'Expressing needs' },
        { char: '何時ですか？', romaji: 'nanji desu ka?', meaning: 'What time is it?', frequency: 10, example: 'Asking for time' }
    ]
};
